# Generated by Django 4.0.2 on 2022-04-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='pcat',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
