# Generated by Django 4.0.2 on 2022-04-25 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_package_pcat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='package',
        ),
    ]
