# Generated by Django 4.0.2 on 2022-04-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App', '0005_delete_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=75)),
                ('pimg', models.ImageField(upload_to='pic')),
                ('pdays', models.CharField(max_length=15)),
                ('pdesc', models.CharField(max_length=600)),
                ('pprice', models.FloatField()),
                ('pcat', models.CharField(max_length=20)),
            ],
        ),
    ]
