# Generated by Django 4.0.2 on 2022-05-03 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=20)),
                ('bemail', models.EmailField(max_length=70)),
                ('bphoneno', models.IntegerField()),
                ('bpersonsno', models.IntegerField()),
                ('bcat', models.CharField(max_length=20)),
                ('bpackname', models.CharField(max_length=75)),
                ('bdays', models.CharField(max_length=15)),
                ('btotalprice', models.FloatField()),
                ('bspreq', models.CharField(max_length=250)),
            ],
        ),
    ]
