# Generated by Django 4.0.2 on 2022-05-10 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='booking',
        ),
    ]
