# Generated by Django 4.0.2 on 2022-05-12 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('uemail', models.EmailField(max_length=80)),
                ('umsg', models.CharField(max_length=600)),
            ],
        ),
    ]
